# Análise de Atendimentos

Este notebook será utilizado para exploração, análise e visualização
dos dados de atendimentos médicos do projeto.

As análises realizadas neste notebook têm finalidade educacional.

In [164]:
import pandas as pd  # Importa a biblioteca Pandas para manipulação e análise dos dados

In [165]:
df = pd.read_csv("../data/raw/atendimentos.csv")  # Carrega o arquivo CSV bruto e armazena os dados em um DataFrame

In [166]:
df  # Exibe todos os registros da base de dados

,id,nome,idade,cidade,especialidade,status,email,telefone,data
0,1,Bruno Lima,30.0,Vinhedo,Clinico Geral,Concluido,bruno.lima@email.com,11999990001,2026-01-15
1,2,Ana Souza,NaN,Campinas,Cardiologia,Agendado,ana.souza@email.com,11999990002,2026-01-20
2,3,Carlos Mendes,40.0,Jundiai,Ortopedia,Cancelado,carlos.mendes@email.com,11999990003,2026-02-05
3,4,Mariana Silva,35.0,Valinhos,Pediatria,Concluido,mariana.silva@email.com,11999990004,2026-02-10
4,5,Joao Santos,52.0,Campinas,Cardiologia,Concluido,joao.santos@email.com,11999990005,2026-02-15
5,5,Joao Santos,52.0,Campinas,Cardiologia,Concluido,joao.santos@email.com,11999990005,2026-02-15
6,6,Pedro Oliveira,28.0,Campinas,Cardiologia,concluido,pedro.oliveira@email.com,11999990006,2026-02-20
7,7,Juliana Costa,45.0,CAMPINAS,cardiologia,AGENDADO,juliana.costa@email.com,11999990007,2026-03-01
8,8,Marcos Pereira,67.0,Campinas,ORTOPEDIA,Cancelado,marcos.pereira@email.com,11999990008,2026-03-05
9,9,Fernanda Alves,29.0,Vinhedo,Dermatologia,Concluido,fernanda.alves@email.com,11999990009,2026-03-10
10,10,Rafael Souza,NaN,Jundiai,Cardiologia,agendado,rafael.souza@email.com,11999990010,2026-03-15
11,11,Patricia Lima,38.0,Campinas,Pediatria,CONCLUIDO,patricia.lima@email.com,11999990011,2026-03-20
12,12,Gabriel Santos,150.0,Valinhos,Ortopedia,Concluido,gabriel.santos@email.com,11999990012,2026-04-01
13,13,Beatriz Oliveira,22.0,Vinhedo,Dermatologia,Cancelado,beatriz.oliveira@email.com,11999990013,2026-04-05
14,14,Lucas Ferreira,41.0,Campinas,Cardiologia,Agendado,lucas.ferreira@email.com,11999990014,2026-04-10
15,15,Amanda Rodrigues,34.0,Campinas,Pediatria,Concluido,amanda.rodrigues@email.com,11999990015,2026-04-15
16,16,Diego Martins,39.0,JUNDIAI,Ortopedia,concluido,diego.martins@email.com,11999990016,2026-04-20
17,17,Carolina Gomes,27.0,Valinhos,Dermatologia,Cancelado,carolina.gomes@email.com,11999990017,2026-05-01
18,18,Thiago Alves,63.0,Campinas,Cardiologia,Concluido,thiago.alves@email.com,11999990018,2026-05-05
19,19,Julio Santos,-5.0,Vinhedo,Clinico Geral,Agendado,julio.santos@email.com,11999990019,2026-05-10
20,20,Renata Costa,31.0,Campinas,Pediatria,Concluido,renata.costa@email.com,11999990020,2026-05-15
21,21,Mariana Silva,35.0,Valinhos,Pediatria,Concluido,mariana.silva@email.com,11999990004,2026-05-20
22,22,Roberto Lima,49.0,Campinas,Cardiologia,Cancelado,roberto.lima@email.com,11999990021,2026-06-01
23,23,Isabela Mendes,26.0,Vinhedo,Dermatologia,Agendado,isabela.mendes@email.com,11999990022,2026-06-05
24,24,Daniel Souza,58.0,Campinas,Cardiologia,Concluido,daniel.souza@email.com,11999990023,2026-06-10
25,25,Vanessa Oliveira,NaN,Valinhos,Pediatria,Agendado,vanessa.oliveira@email.com,11999990024,2026-06-15
26,26,Andre Pereira,36.0,Campinas,Ortopedia,Concluido,andre.pereira@email.com,11999990025,2026-06-20
27,27,Paula Fernandes,43.0,Vinhedo,Dermatologia,CONCLUIDO,paula.fernandes@email.com,11999990026,2026-07-01
28,28,Mateus Costa,19.0,Campinas,Clinico Geral,Cancelado,mateus.costa@email.com,11999990027,2026-07-05
29,29,Lucas Ferreira,41.0,Campinas,Cardiologia,Agendado,lucas.ferreira@email.com,11999990014,2026-07-10
30,30,Joana Alves,33.0,Valinhos,Pediatria,Concluido,joana.alves@email.com,11999990028,2026-07-15

In [ ]:
df.shape  # Quantas linhas e colunas existem na nossa base?

(31, 8)

In [ ]:
df.info()  # Quais são os tipos de dados e a quantidade de valores preenchidos em cada coluna?

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             31 non-null     int64
 1   nome           31 non-null     str
 2   idade          28 non-null     float64
 3   cidade         31 non-null     str
 4   especialidade  31 non-null     str
 5   status         31 non-null     str
 6   email          31 non-null     str
 7   telefone       31 non-null     int64
dtypes: float64(1), int64(2), str(5)
memory usage: 2.1 KB

In [ ]:
df.describe()  # Qual é o resumo estatístico das colunas numéricas da nossa base?

              id       idade      telefone
count  31.000000   28.000000  3.100000e+01
mean   15.161290   41.357143  1.199999e+10
std     8.858505   25.670583  8.193887e+00
min     1.000000   -5.000000  1.199999e+10
25%     7.500000   29.750000  1.199999e+10
50%    15.000000   37.000000  1.199999e+10
75%    22.500000   46.000000  1.199999e+10
max    30.000000  150.000000  1.199999e+10

In [ ]:
df.isnull().sum()  # Quantos valores ausentes existem em cada coluna da nossa base?

id               0
nome             0
idade            3
cidade           0
especialidade    0
status           0
email            0
telefone         0
dtype: int64

In [ ]:
df["status"].unique()  # Quais são os diferentes status existentes na nossa base?

<StringArray>
['Concluido',  'Agendado', 'Cancelado', 'concluido',  'AGENDADO',  'agendado',
 'CONCLUIDO']
Length: 7, dtype: str

In [ ]:
df["status"].value_counts()  # Qual é o status mais frequente na nossa base?

status
Concluido    13
Agendado      6
Cancelado     6
concluido     2
CONCLUIDO     2
AGENDADO      1
agendado      1
Name: count, dtype: int64

In [ ]:
df["especialidade"].value_counts()  # Qual especialidade possui mais registros na nossa base?

especialidade
Cardiologia      10
Pediatria         6
Dermatologia      5
Ortopedia         4
Clinico Geral     3
cardiologia       1
ORTOPEDIA         1
 Pediatria        1
Name: count, dtype: int64

In [ ]:
df["cidade"].value_counts()  # Qual cidade possui mais registros na nossa base?

cidade
Campinas      13
Vinhedo        6
Valinhos       5
Jundiai        2
 Valinhos      1
CAMPINAS       1
 Campinas      1
 Campinas      1
JUNDIAI        1
Name: count, dtype: int64

In [ ]:
len(df)  # Quantos registros existem na nossa base?

31

In [ ]:
df["idade"].mean()  # Qual é a idade média dos pacientes?

np.float64(41.357142857142854)

In [ ]:
df["idade"].min()  # Qual é a menor idade registrada na nossa base?

np.float64(-5.0)

In [ ]:
df["idade"].max()  # Qual é a maior idade registrada na nossa base?

np.float64(150.0)

In [ ]:
df[df["idade"].isnull()]  # Quais registros possuem valores ausentes na coluna idade?

Empty DataFrame
Columns: [id, nome, idade, cidade, especialidade, status, email, telefone]
Index: []

In [ ]:
df["idade"].median()  # Qual é a idade mediana dos pacientes?

np.float64(37.0)

In [ ]:
df["idade"] = df["idade"].fillna(df["idade"].median())  # Como preencher os valores ausentes de idade usando a mediana?

In [ ]:
df[df["idade"] > 100]  # Existem pacientes com idade superior a 100 anos?

,id,nome,idade,cidade,especialidade,status,email,telefone
12,12,Gabriel Santos,150.0,Valinhos,Ortopedia,Concluido,gabriel.santos@email.com,11999990012

In [ ]:
df[df["idade"] < 0]  # Existem registros com idade menor que zero?

,id,nome,idade,cidade,especialidade,status,email,telefone
19,19,Julio Santos,-5.0,Vinhedo,Clinico Geral,Agendado,julio.santos@email.com,11999990019

In [ ]:
df[(df["idade"] < 0) | (df["idade"] > 100)]  # Existem registros com idade inválida, menor que 0 ou maior que 100?

,id,nome,idade,cidade,especialidade,status,email,telefone
12,12,Gabriel Santos,150.0,Valinhos,Ortopedia,Concluido,gabriel.santos@email.com,11999990012
19,19,Julio Santos,-5.0,Vinhedo,Clinico Geral,Agendado,julio.santos@email.com,11999990019

In [ ]:
df.loc[(df["idade"] < 0) | (df["idade"] > 100), "idade"] = pd.NA  # Substitui as idades inválidas por valores ausentes

In [ ]:
df["cidade"].unique()  # Quais são os diferentes valores de cidade existentes na nossa base?

<StringArray>
[   'Vinhedo',   'Campinas',    'Jundiai', ' Valinhos ',   'CAMPINAS',
 ' Campinas ',   'Valinhos',  ' Campinas',    'JUNDIAI']
Length: 9, dtype: str

In [ ]:
df["cidade"] = df["cidade"].str.strip()  # Remove espaços extras no início e no final dos nomes das cidades

In [ ]:
df["cidade"] = df["cidade"].str.lower()  # Padroniza os nomes das cidades para letras minúsculas

In [ ]:
df["especialidade"] = df["especialidade"].str.strip()  # Remove espaços extras no início e no final das especialidades

In [ ]:
df["especialidade"] = df["especialidade"].str.lower()  # Padroniza os nomes das especialidades para letras minúsculas

In [ ]:
df["especialidade"].unique()  # Quais são os diferentes valores de especialidade existentes na nossa base?

<StringArray>
['clinico geral', 'cardiologia', 'ortopedia', 'pediatria', 'dermatologia']
Length: 5, dtype: str

In [ ]:
df["status"] = df["status"].str.strip()  # Remove espaços extras no início e no final dos status

In [ ]:
df["status"] = df["status"].str.lower()  # Padroniza os valores de status para letras minúsculas

In [ ]:
df["status"].unique()  # Quais são os diferentes valores de status existentes na nossa base?

<StringArray>
['concluido', 'agendado', 'cancelado']
Length: 3, dtype: str

In [ ]:
df[df["email"].duplicated(keep=False)]  # Quais registros possuem emails duplicados na nossa base?

,id,nome,idade,cidade,especialidade,status,email,telefone
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
5,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
14,14,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014
29,29,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014

In [ ]:
df[df["telefone"].duplicated(keep=False)]  # Quais registros possuem telefones duplicados na nossa base?

,id,nome,idade,cidade,especialidade,status,email,telefone
3,4,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
21,21,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004

In [ ]:
df = df.drop_duplicates(subset="email")  # Remove registros duplicados considerando o email como identificador

In [ ]:
df.drop_duplicates(subset="email", keep="first")  # Remove duplicados pelo email mantendo apenas o primeiro registro

,id,nome,idade,cidade,especialidade,status,email,telefone
0,1,Bruno Lima,30.0,vinhedo,clinico geral,concluido,bruno.lima@email.com,11999990001
1,2,Ana Souza,37.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002
2,3,Carlos Mendes,40.0,jundiai,ortopedia,cancelado,carlos.mendes@email.com,11999990003
3,4,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
6,6,Pedro Oliveira,28.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006
7,7,Juliana Costa,45.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008
9,9,Fernanda Alves,29.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009
10,10,Rafael Souza,37.0,jundiai,cardiologia,agendado,rafael.souza@email.com,11999990010
11,11,Patricia Lima,38.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011
12,12,Gabriel Santos,NaN,valinhos,ortopedia,concluido,gabriel.santos@email.com,11999990012
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013
14,14,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014
15,15,Amanda Rodrigues,34.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015
16,16,Diego Martins,39.0,jundiai,ortopedia,concluido,diego.martins@email.com,11999990016
17,17,Carolina Gomes,27.0,valinhos,dermatologia,cancelado,carolina.gomes@email.com,11999990017
18,18,Thiago Alves,63.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018
19,19,Julio Santos,NaN,vinhedo,clinico geral,agendado,julio.santos@email.com,11999990019
20,20,Renata Costa,31.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020
21,21,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
22,22,Roberto Lima,49.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021
23,23,Isabela Mendes,26.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022
24,24,Daniel Souza,58.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023
25,25,Vanessa Oliveira,37.0,valinhos,pediatria,agendado,vanessa.oliveira@email.com,11999990024
26,26,Andre Pereira,36.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025
27,27,Paula Fernandes,43.0,vinhedo,dermatologia,concluido,paula.fernandes@email.com,11999990026
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027
30,30,Joana Alves,33.0,valinhos,pediatria,concluido,joana.alves@email.com,11999990028

In [ ]:
df["cidade"].value_counts()  # Qual cidade possui mais registros na nossa base?

cidade
campinas    14
vinhedo      6
valinhos     6
jundiai      3
Name: count, dtype: int64

In [ ]:
df["especialidade"].value_counts()  # Qual especialidade possui mais registros na nossa base?

especialidade
cardiologia      9
pediatria        7
ortopedia        5
dermatologia     5
clinico geral    3
Name: count, dtype: int64

In [ ]:
df["status"].value_counts()  # Qual é o status mais frequente na nossa base?

status
concluido    16
agendado      7
cancelado     6
Name: count, dtype: int64

In [ ]:
df["status"].value_counts()["cancelado"]  # Quantos registros possuem o status cancelado?

np.int64(6)

In [ ]:
df["cidade"].value_counts().idxmax()  # Qual é a cidade com a maior quantidade de registros?

'campinas'

In [ ]:
df["cidade"].value_counts().max()  # Qual é a maior quantidade de registros encontrada em uma cidade?

np.int64(14)

In [ ]:
print("Atendimentos por cidade:")  # Exibe o título da análise de atendimentos por cidade
df["cidade"].value_counts()  # Quantos atendimentos existem em cada cidade?

Atendimentos por cidade:

cidade
campinas    14
vinhedo      6
valinhos     6
jundiai      3
Name: count, dtype: int64

In [ ]:
print("Atendimentos por especialidade:")  # Exibe o título da análise de atendimentos por especialidade
df["especialidade"].value_counts()  # Quantos atendimentos existem em cada especialidade?

Atendimentos por especialidade:

especialidade
cardiologia      9
pediatria        7
ortopedia        5
dermatologia     5
clinico geral    3
Name: count, dtype: int64

In [ ]:
print("Atendimentos por status:")  # Exibe o título da análise de atendimentos por status
df["status"].value_counts()  # Quantos atendimentos existem em cada status?

Atendimentos por status:

status
concluido    16
agendado      7
cancelado     6
Name: count, dtype: int64

In [ ]:
df["status"].value_counts()  # Qual é o status mais frequente?

status
concluido    16
agendado      7
cancelado     6
Name: count, dtype: int64

In [51]:
df.groupby("cidade")["idade"].mean()  # Qual é a idade média dos pacientes em cada cidade?

cidade
campinas    42.714286
jundiai     38.666667
valinhos    33.400000
vinhedo     30.000000
Name: idade, dtype: float64

In [53]:
df.groupby("cidade")["idade"].count()  # Quantos pacientes possuem idade registrada em cada cidade?

cidade
campinas    14
jundiai      3
valinhos     5
vinhedo      5
Name: idade, dtype: int64

In [54]:
df.groupby("especialidade")["idade"].mean()  # Qual é a idade média dos pacientes em cada especialidade?

especialidade
cardiologia      45.555556
clinico geral    24.500000
dermatologia     29.400000
ortopedia        45.500000
pediatria        34.714286
Name: idade, dtype: float64

In [55]:
df.groupby(["cidade", "status"]).size()  # Quantos atendimentos existem em cada cidade para cada status?

cidade    status
campinas  agendado     3
          cancelado    3
          concluido    8
jundiai   agendado     1
          cancelado    1
          concluido    1
valinhos  agendado     1
          cancelado    1
          concluido    4
vinhedo   agendado     2
          cancelado    1
          concluido    3
dtype: int64

In [56]:
df.groupby(["cidade", "status"]).size().unstack(fill_value=0)  # Como os atendimentos estão distribuídos por cidade e status?

status    agendado  cancelado  concluido
cidade
campinas         3          3          8
jundiai          1          1          1
valinhos         1          1          4
vinhedo          2          1          3

In [57]:
df.groupby("cidade")["idade"].agg(["count", "mean", "min", "max"])  # Qual é o resumo das idades dos pacientes em cada cidade?

          count       mean   min   max
cidade
campinas     14  42.714286  19.0  67.0
jundiai       3  38.666667  37.0  40.0
valinhos      5  33.400000  27.0  37.0
vinhedo       5  30.000000  22.0  43.0

In [58]:
df.groupby("cidade")["idade"].agg(["count", "mean", "min", "max"])  # Qual é o resumo das idades dos pacientes em cada cidade?

          count       mean   min   max
cidade
campinas     14  42.714286  19.0  67.0
jundiai       3  38.666667  37.0  40.0
valinhos      5  33.400000  27.0  37.0
vinhedo       5  30.000000  22.0  43.0

In [63]:
df["idade"].agg([
    "sum",       # Qual é a soma de todas as idades registradas?
    "mean",      # Qual é a idade média dos pacientes?
    "median",    # Qual é a idade que divide os pacientes ao meio?
    "min",       # Qual é a menor idade registrada?
    "max",       # Qual é a maior idade registrada?
    "std",       # Qual é o nível de variação das idades em relação à média?
    "var"        # Qual é a variância das idades registradas?
])  # Quais são as principais estatísticas da distribuição das idades?

sum       1031.000000
mean        38.185185
median      37.000000
min         19.000000
max         67.000000
std         11.622382
var        135.079772
Name: idade, dtype: float64

In [61]:
df["idade"].agg([
    "count",      # Quantos pacientes possuem idade registrada?
    "mean",       # Qual é a idade média?
    "median",     # Qual é a idade central?
    "min",        # Qual é a menor idade?
    "max",        # Qual é a maior idade?
    "std"         # Quanto as idades variam em relação à média?
])  # Qual é o resumo principal das idades dos pacientes?

count     27.000000
mean      38.185185
median    37.000000
min       19.000000
max       67.000000
std       11.622382
Name: idade, dtype: float64

In [64]:
df.groupby("cidade")["idade"].mean().sort_values()  # Qual cidade possui a menor idade média dos pacientes?

cidade
vinhedo     30.000000
valinhos    33.400000
jundiai     38.666667
campinas    42.714286
Name: idade, dtype: float64

In [65]:
df.groupby("cidade")["idade"].mean().sort_values(ascending=False)  # Qual cidade possui a maior idade média dos pacientes?

cidade
campinas    42.714286
jundiai     38.666667
valinhos    33.400000
vinhedo     30.000000
Name: idade, dtype: float64

In [66]:
df.sort_values("idade")  # Quais são os registros ordenados da menor para a maior idade?

,id,nome,idade,cidade,especialidade,status,email,telefone
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013
23,23,Isabela Mendes,26.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022
17,17,Carolina Gomes,27.0,valinhos,dermatologia,cancelado,carolina.gomes@email.com,11999990017
6,6,Pedro Oliveira,28.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006
9,9,Fernanda Alves,29.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009
0,1,Bruno Lima,30.0,vinhedo,clinico geral,concluido,bruno.lima@email.com,11999990001
20,20,Renata Costa,31.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020
30,30,Joana Alves,33.0,valinhos,pediatria,concluido,joana.alves@email.com,11999990028
15,15,Amanda Rodrigues,34.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015
3,4,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
21,21,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
26,26,Andre Pereira,36.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025
25,25,Vanessa Oliveira,37.0,valinhos,pediatria,agendado,vanessa.oliveira@email.com,11999990024
10,10,Rafael Souza,37.0,jundiai,cardiologia,agendado,rafael.souza@email.com,11999990010
1,2,Ana Souza,37.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002
11,11,Patricia Lima,38.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011
16,16,Diego Martins,39.0,jundiai,ortopedia,concluido,diego.martins@email.com,11999990016
2,3,Carlos Mendes,40.0,jundiai,ortopedia,cancelado,carlos.mendes@email.com,11999990003
14,14,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014
27,27,Paula Fernandes,43.0,vinhedo,dermatologia,concluido,paula.fernandes@email.com,11999990026
7,7,Juliana Costa,45.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007
22,22,Roberto Lima,49.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
24,24,Daniel Souza,58.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023
18,18,Thiago Alves,63.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008
12,12,Gabriel Santos,NaN,valinhos,ortopedia,concluido,gabriel.santos@email.com,11999990012
19,19,Julio Santos,NaN,vinhedo,clinico geral,agendado,julio.santos@email.com,11999990019

In [67]:
df.sort_values("idade", ascending=False)  # Quais são os registros ordenados da maior para a menor idade?

,id,nome,idade,cidade,especialidade,status,email,telefone
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008
18,18,Thiago Alves,63.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018
24,24,Daniel Souza,58.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
22,22,Roberto Lima,49.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021
7,7,Juliana Costa,45.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007
27,27,Paula Fernandes,43.0,vinhedo,dermatologia,concluido,paula.fernandes@email.com,11999990026
14,14,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014
2,3,Carlos Mendes,40.0,jundiai,ortopedia,cancelado,carlos.mendes@email.com,11999990003
16,16,Diego Martins,39.0,jundiai,ortopedia,concluido,diego.martins@email.com,11999990016
11,11,Patricia Lima,38.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011
1,2,Ana Souza,37.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002
10,10,Rafael Souza,37.0,jundiai,cardiologia,agendado,rafael.souza@email.com,11999990010
25,25,Vanessa Oliveira,37.0,valinhos,pediatria,agendado,vanessa.oliveira@email.com,11999990024
26,26,Andre Pereira,36.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025
21,21,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
3,4,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
15,15,Amanda Rodrigues,34.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015
30,30,Joana Alves,33.0,valinhos,pediatria,concluido,joana.alves@email.com,11999990028
20,20,Renata Costa,31.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020
0,1,Bruno Lima,30.0,vinhedo,clinico geral,concluido,bruno.lima@email.com,11999990001
9,9,Fernanda Alves,29.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009
6,6,Pedro Oliveira,28.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006
17,17,Carolina Gomes,27.0,valinhos,dermatologia,cancelado,carolina.gomes@email.com,11999990017
23,23,Isabela Mendes,26.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027
12,12,Gabriel Santos,NaN,valinhos,ortopedia,concluido,gabriel.santos@email.com,11999990012
19,19,Julio Santos,NaN,vinhedo,clinico geral,agendado,julio.santos@email.com,11999990019

In [68]:
df.sort_values(["cidade", "idade"])  # Como os pacientes estão ordenados por cidade e depois por idade?

,id,nome,idade,cidade,especialidade,status,email,telefone
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027
6,6,Pedro Oliveira,28.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006
20,20,Renata Costa,31.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020
15,15,Amanda Rodrigues,34.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015
26,26,Andre Pereira,36.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025
1,2,Ana Souza,37.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002
11,11,Patricia Lima,38.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011
14,14,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014
7,7,Juliana Costa,45.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007
22,22,Roberto Lima,49.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
24,24,Daniel Souza,58.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023
18,18,Thiago Alves,63.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008
10,10,Rafael Souza,37.0,jundiai,cardiologia,agendado,rafael.souza@email.com,11999990010
16,16,Diego Martins,39.0,jundiai,ortopedia,concluido,diego.martins@email.com,11999990016
2,3,Carlos Mendes,40.0,jundiai,ortopedia,cancelado,carlos.mendes@email.com,11999990003
17,17,Carolina Gomes,27.0,valinhos,dermatologia,cancelado,carolina.gomes@email.com,11999990017
30,30,Joana Alves,33.0,valinhos,pediatria,concluido,joana.alves@email.com,11999990028
3,4,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
21,21,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
25,25,Vanessa Oliveira,37.0,valinhos,pediatria,agendado,vanessa.oliveira@email.com,11999990024
12,12,Gabriel Santos,NaN,valinhos,ortopedia,concluido,gabriel.santos@email.com,11999990012
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013
23,23,Isabela Mendes,26.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022
9,9,Fernanda Alves,29.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009
0,1,Bruno Lima,30.0,vinhedo,clinico geral,concluido,bruno.lima@email.com,11999990001
27,27,Paula Fernandes,43.0,vinhedo,dermatologia,concluido,paula.fernandes@email.com,11999990026
19,19,Julio Santos,NaN,vinhedo,clinico geral,agendado,julio.santos@email.com,11999990019

In [69]:
df.sort_values(["cidade", "idade"], ascending=[True, False])  # Como ordenar as cidades em ordem crescente e as idades em ordem decrescente?

,id,nome,idade,cidade,especialidade,status,email,telefone
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008
18,18,Thiago Alves,63.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018
24,24,Daniel Souza,58.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
22,22,Roberto Lima,49.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021
7,7,Juliana Costa,45.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007
14,14,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014
11,11,Patricia Lima,38.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011
1,2,Ana Souza,37.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002
26,26,Andre Pereira,36.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025
15,15,Amanda Rodrigues,34.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015
20,20,Renata Costa,31.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020
6,6,Pedro Oliveira,28.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027
2,3,Carlos Mendes,40.0,jundiai,ortopedia,cancelado,carlos.mendes@email.com,11999990003
16,16,Diego Martins,39.0,jundiai,ortopedia,concluido,diego.martins@email.com,11999990016
10,10,Rafael Souza,37.0,jundiai,cardiologia,agendado,rafael.souza@email.com,11999990010
25,25,Vanessa Oliveira,37.0,valinhos,pediatria,agendado,vanessa.oliveira@email.com,11999990024
3,4,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
21,21,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004
30,30,Joana Alves,33.0,valinhos,pediatria,concluido,joana.alves@email.com,11999990028
17,17,Carolina Gomes,27.0,valinhos,dermatologia,cancelado,carolina.gomes@email.com,11999990017
12,12,Gabriel Santos,NaN,valinhos,ortopedia,concluido,gabriel.santos@email.com,11999990012
27,27,Paula Fernandes,43.0,vinhedo,dermatologia,concluido,paula.fernandes@email.com,11999990026
0,1,Bruno Lima,30.0,vinhedo,clinico geral,concluido,bruno.lima@email.com,11999990001
9,9,Fernanda Alves,29.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009
23,23,Isabela Mendes,26.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013
19,19,Julio Santos,NaN,vinhedo,clinico geral,agendado,julio.santos@email.com,11999990019

In [70]:
df.groupby("cidade")["idade"].agg(["count", "mean", "min", "max"]).sort_values("mean", ascending=False)  # Quais cidades possuem as maiores idades médias dos pacientes?

          count       mean   min   max
cidade
campinas     14  42.714286  19.0  67.0
jundiai       3  38.666667  37.0  40.0
valinhos      5  33.400000  27.0  37.0
vinhedo       5  30.000000  22.0  43.0

In [71]:
df[df["idade"] > 50]  # Quais pacientes possuem mais de 50 anos?

,id,nome,idade,cidade,especialidade,status,email,telefone
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008
18,18,Thiago Alves,63.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018
24,24,Daniel Souza,58.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023

In [72]:
df.loc[df["idade"] > 50, ["nome", "idade", "cidade"]]  # Quais são os pacientes com mais de 50 anos e suas respectivas cidades?

              nome  idade    cidade
4      Joao Santos   52.0  campinas
8   Marcos Pereira   67.0  campinas
18    Thiago Alves   63.0  campinas
24    Daniel Souza   58.0  campinas

In [73]:
df.loc[df["status"] == "cancelado"]  # Quais atendimentos possuem status cancelado?

,id,nome,idade,cidade,especialidade,status,email,telefone
2,3,Carlos Mendes,40.0,jundiai,ortopedia,cancelado,carlos.mendes@email.com,11999990003
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013
17,17,Carolina Gomes,27.0,valinhos,dermatologia,cancelado,carolina.gomes@email.com,11999990017
22,22,Roberto Lima,49.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027

In [74]:
df.loc[df["status"] == "cancelado", ["nome", "especialidade", "status"]]  # Quais pacientes possuem atendimentos cancelados e quais são suas especialidades?

                nome  especialidade     status
2      Carlos Mendes      ortopedia  cancelado
8     Marcos Pereira      ortopedia  cancelado
13  Beatriz Oliveira   dermatologia  cancelado
17    Carolina Gomes   dermatologia  cancelado
22      Roberto Lima    cardiologia  cancelado
28      Mateus Costa  clinico geral  cancelado

In [75]:
df.loc[(df["idade"] > 50) & (df["status"] == "cancelado")]  # Quais pacientes com mais de 50 anos possuem atendimentos cancelados?

,id,nome,idade,cidade,especialidade,status,email,telefone
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008

In [76]:
df.loc[(df["cidade"] == "campinas") | (df["cidade"] == "vinhedo")]  # Quais pacientes são de Campinas ou Vinhedo?

,id,nome,idade,cidade,especialidade,status,email,telefone
0,1,Bruno Lima,30.0,vinhedo,clinico geral,concluido,bruno.lima@email.com,11999990001
1,2,Ana Souza,37.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005
6,6,Pedro Oliveira,28.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006
7,7,Juliana Costa,45.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008
9,9,Fernanda Alves,29.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009
11,11,Patricia Lima,38.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013
14,14,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014
15,15,Amanda Rodrigues,34.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015
18,18,Thiago Alves,63.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018
19,19,Julio Santos,NaN,vinhedo,clinico geral,agendado,julio.santos@email.com,11999990019
20,20,Renata Costa,31.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020
22,22,Roberto Lima,49.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021
23,23,Isabela Mendes,26.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022
24,24,Daniel Souza,58.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023
26,26,Andre Pereira,36.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025
27,27,Paula Fernandes,43.0,vinhedo,dermatologia,concluido,paula.fernandes@email.com,11999990026
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027

In [77]:
df.loc[(df["idade"] >= 18) & (df["idade"] <= 30), ["nome", "idade", "cidade"]]  # Quais são os pacientes com idade entre 18 e 30 anos e suas respectivas cidades?

                nome  idade    cidade
0         Bruno Lima   30.0   vinhedo
6     Pedro Oliveira   28.0  campinas
9     Fernanda Alves   29.0   vinhedo
13  Beatriz Oliveira   22.0   vinhedo
17    Carolina Gomes   27.0  valinhos
23    Isabela Mendes   26.0   vinhedo
28      Mateus Costa   19.0  campinas

In [78]:
df.loc[(df["idade"] < 0) | (df["idade"] > 100), "idade"] = pd.NA  # Substitui idades inválidas por valores ausentes

In [79]:
df["faixa_etaria"] = "adulto"  # Define inicialmente todos os pacientes como adultos

In [80]:
df.loc[df["idade"] < 18, "faixa_etaria"] = "menor de idade"  # Classifica pacientes menores de 18 anos

In [81]:
df.loc[df["idade"] >= 60, "faixa_etaria"] = "idoso"  # Classifica pacientes com 60 anos ou mais

In [82]:
df["faixa_etaria"].value_counts()  # Quantos pacientes existem em cada faixa etária?

faixa_etaria
adulto    27
idoso      2
Name: count, dtype: int64

In [83]:
df.groupby(["faixa_etaria", "status"]).size()  # Quantos atendimentos existem por faixa etária e status?

faixa_etaria  status
adulto        agendado      7
              cancelado     5
              concluido    15
idoso         cancelado     1
              concluido     1
dtype: int64

In [84]:
df.groupby(["faixa_etaria", "status"]).size().unstack(fill_value=0)  # Como os atendimentos estão distribuídos por faixa etária e status?

status        agendado  cancelado  concluido
faixa_etaria
adulto               7          5         15
idoso                0          1          1

In [85]:
df.loc[df["cidade"].isin(["campinas", "vinhedo"])]  # Quais pacientes são de Campinas ou Vinhedo?

,id,nome,idade,cidade,especialidade,status,email,telefone,faixa_etaria
0,1,Bruno Lima,30.0,vinhedo,clinico geral,concluido,bruno.lima@email.com,11999990001,adulto
1,2,Ana Souza,37.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002,adulto
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005,adulto
6,6,Pedro Oliveira,28.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006,adulto
7,7,Juliana Costa,45.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007,adulto
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008,idoso
9,9,Fernanda Alves,29.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009,adulto
11,11,Patricia Lima,38.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011,adulto
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013,adulto
14,14,Lucas Ferreira,41.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014,adulto
15,15,Amanda Rodrigues,34.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015,adulto
18,18,Thiago Alves,63.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018,idoso
19,19,Julio Santos,NaN,vinhedo,clinico geral,agendado,julio.santos@email.com,11999990019,adulto
20,20,Renata Costa,31.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020,adulto
22,22,Roberto Lima,49.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021,adulto
23,23,Isabela Mendes,26.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022,adulto
24,24,Daniel Souza,58.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023,adulto
26,26,Andre Pereira,36.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025,adulto
27,27,Paula Fernandes,43.0,vinhedo,dermatologia,concluido,paula.fernandes@email.com,11999990026,adulto
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027,adulto

In [86]:
df.loc[df["status"].isin(["cancelado", "concluido"])]  # Quais atendimentos estão cancelados ou concluídos?

,id,nome,idade,cidade,especialidade,status,email,telefone,faixa_etaria
0,1,Bruno Lima,30.0,vinhedo,clinico geral,concluido,bruno.lima@email.com,11999990001,adulto
2,3,Carlos Mendes,40.0,jundiai,ortopedia,cancelado,carlos.mendes@email.com,11999990003,adulto
3,4,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004,adulto
4,5,Joao Santos,52.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005,adulto
6,6,Pedro Oliveira,28.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006,adulto
8,8,Marcos Pereira,67.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008,idoso
9,9,Fernanda Alves,29.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009,adulto
11,11,Patricia Lima,38.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011,adulto
12,12,Gabriel Santos,NaN,valinhos,ortopedia,concluido,gabriel.santos@email.com,11999990012,adulto
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013,adulto
15,15,Amanda Rodrigues,34.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015,adulto
16,16,Diego Martins,39.0,jundiai,ortopedia,concluido,diego.martins@email.com,11999990016,adulto
17,17,Carolina Gomes,27.0,valinhos,dermatologia,cancelado,carolina.gomes@email.com,11999990017,adulto
18,18,Thiago Alves,63.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018,idoso
20,20,Renata Costa,31.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020,adulto
21,21,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004,adulto
22,22,Roberto Lima,49.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021,adulto
24,24,Daniel Souza,58.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023,adulto
26,26,Andre Pereira,36.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025,adulto
27,27,Paula Fernandes,43.0,vinhedo,dermatologia,concluido,paula.fernandes@email.com,11999990026,adulto
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027,adulto
30,30,Joana Alves,33.0,valinhos,pediatria,concluido,joana.alves@email.com,11999990028,adulto

In [87]:
df.loc[
    df["status"].isin(["cancelado", "concluido"]),
    ["nome", "especialidade", "status"]
]  # Quais pacientes possuem atendimentos cancelados ou concluídos?

                nome  especialidade     status
0         Bruno Lima  clinico geral  concluido
2      Carlos Mendes      ortopedia  cancelado
3     Mariana Silva       pediatria  concluido
4        Joao Santos    cardiologia  concluido
6     Pedro Oliveira    cardiologia  concluido
8     Marcos Pereira      ortopedia  cancelado
9     Fernanda Alves   dermatologia  concluido
11     Patricia Lima      pediatria  concluido
12    Gabriel Santos      ortopedia  concluido
13  Beatriz Oliveira   dermatologia  cancelado
15  Amanda Rodrigues      pediatria  concluido
16     Diego Martins      ortopedia  concluido
17    Carolina Gomes   dermatologia  cancelado
18      Thiago Alves    cardiologia  concluido
20      Renata Costa      pediatria  concluido
21     Mariana Silva      pediatria  concluido
22      Roberto Lima    cardiologia  cancelado
24      Daniel Souza    cardiologia  concluido
26     Andre Pereira      ortopedia  concluido
27   Paula Fernandes   dermatologia  concluido
28      Mateus Costa  clinico geral  cancelado
30       Joana Alves      pediatria  concluido

In [88]:
df.loc[
    ~df["cidade"].isin(["campinas", "vinhedo"])
]  # Quais pacientes não são de Campinas nem de Vinhedo?

,id,nome,idade,cidade,especialidade,status,email,telefone,faixa_etaria
2,3,Carlos Mendes,40.0,jundiai,ortopedia,cancelado,carlos.mendes@email.com,11999990003,adulto
3,4,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004,adulto
10,10,Rafael Souza,37.0,jundiai,cardiologia,agendado,rafael.souza@email.com,11999990010,adulto
12,12,Gabriel Santos,NaN,valinhos,ortopedia,concluido,gabriel.santos@email.com,11999990012,adulto
16,16,Diego Martins,39.0,jundiai,ortopedia,concluido,diego.martins@email.com,11999990016,adulto
17,17,Carolina Gomes,27.0,valinhos,dermatologia,cancelado,carolina.gomes@email.com,11999990017,adulto
21,21,Mariana Silva,35.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004,adulto
25,25,Vanessa Oliveira,37.0,valinhos,pediatria,agendado,vanessa.oliveira@email.com,11999990024,adulto
30,30,Joana Alves,33.0,valinhos,pediatria,concluido,joana.alves@email.com,11999990028,adulto

In [89]:
df.loc[
    df["idade"].between(18, 30)
]  # Quais pacientes possuem entre 18 e 30 anos?

,id,nome,idade,cidade,especialidade,status,email,telefone,faixa_etaria
0,1,Bruno Lima,30.0,vinhedo,clinico geral,concluido,bruno.lima@email.com,11999990001,adulto
6,6,Pedro Oliveira,28.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006,adulto
9,9,Fernanda Alves,29.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009,adulto
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013,adulto
17,17,Carolina Gomes,27.0,valinhos,dermatologia,cancelado,carolina.gomes@email.com,11999990017,adulto
23,23,Isabela Mendes,26.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022,adulto
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027,adulto

In [ ]:
df.loc[
    df["idade"].between(18, 30, inclusive="neither")
]  # Quais pacientes possuem idade entre 18 e 30 anos sem incluir os limites? 18 < idade < 30

,id,nome,idade,cidade,especialidade,status,email,telefone,faixa_etaria
6,6,Pedro Oliveira,28.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006,adulto
9,9,Fernanda Alves,29.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009,adulto
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013,adulto
17,17,Carolina Gomes,27.0,valinhos,dermatologia,cancelado,carolina.gomes@email.com,11999990017,adulto
23,23,Isabela Mendes,26.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022,adulto
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027,adulto

In [91]:
df.loc[
    df["idade"].between(18, 30, inclusive="left")
]  # Quais pacientes possuem idade entre 18 e 30 anos sem incluir os limites? 18 <= idade < 30

,id,nome,idade,cidade,especialidade,status,email,telefone,faixa_etaria
6,6,Pedro Oliveira,28.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006,adulto
9,9,Fernanda Alves,29.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009,adulto
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013,adulto
17,17,Carolina Gomes,27.0,valinhos,dermatologia,cancelado,carolina.gomes@email.com,11999990017,adulto
23,23,Isabela Mendes,26.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022,adulto
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027,adulto

In [92]:
df.loc[
    df["idade"].between(18, 30, inclusive="right")
]  # Quais pacientes possuem idade entre 18 e 30 anos sem incluir os limites? 18 < idade <= 30

,id,nome,idade,cidade,especialidade,status,email,telefone,faixa_etaria
0,1,Bruno Lima,30.0,vinhedo,clinico geral,concluido,bruno.lima@email.com,11999990001,adulto
6,6,Pedro Oliveira,28.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006,adulto
9,9,Fernanda Alves,29.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009,adulto
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013,adulto
17,17,Carolina Gomes,27.0,valinhos,dermatologia,cancelado,carolina.gomes@email.com,11999990017,adulto
23,23,Isabela Mendes,26.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022,adulto
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027,adulto

In [93]:
df.loc[
    df["cidade"].isin(["campinas", "vinhedo"]) &
    df["idade"].between(18, 40)
]  # Quais pacientes de Campinas ou Vinhedo possuem entre 18 e 40 anos?

,id,nome,idade,cidade,especialidade,status,email,telefone,faixa_etaria
0,1,Bruno Lima,30.0,vinhedo,clinico geral,concluido,bruno.lima@email.com,11999990001,adulto
1,2,Ana Souza,37.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002,adulto
6,6,Pedro Oliveira,28.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006,adulto
9,9,Fernanda Alves,29.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009,adulto
11,11,Patricia Lima,38.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011,adulto
13,13,Beatriz Oliveira,22.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013,adulto
15,15,Amanda Rodrigues,34.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015,adulto
20,20,Renata Costa,31.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020,adulto
23,23,Isabela Mendes,26.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022,adulto
26,26,Andre Pereira,36.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025,adulto
28,28,Mateus Costa,19.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027,adulto

In [94]:
df.loc[
    df["idade"].between(18, 40)
].groupby("cidade").size()  # Quantos pacientes entre 18 e 40 anos existem em cada cidade?

cidade
campinas    7
jundiai     3
valinhos    5
vinhedo     4
dtype: int64

In [95]:
df.loc[
    df["status"].isin(["cancelado", "concluido"])
].groupby("especialidade").size()  # Quantos atendimentos cancelados ou concluídos existem por especialidade?

especialidade
cardiologia      5
clinico geral    2
dermatologia     4
ortopedia        5
pediatria        6
dtype: int64

In [96]:
df["faixa_etaria"] = "adulto"  # DataFrame, crie a coluna faixa_etaria e defina inicialmente todos os usuários como adultos.

In [97]:
df.loc[df["idade"] < 18, "faixa_etaria"] = "menor de idade"  # DataFrame, localize na coluna idade os usuários menores de 18 anos e altere a faixa_etaria para menor de idade.

In [98]:
df.loc[df["idade"] >= 60, "faixa_etaria"] = "idoso"  # DataFrame, localize na coluna idade os usuários com 60 anos ou mais e altere a faixa_etaria para idoso.

In [99]:
df["faixa_etaria"].unique()  # Na coluna faixa_etaria, quais são as categorias de idade existentes?

<StringArray>
['adulto', 'idoso']
Length: 2, dtype: str

In [101]:
df["faixa_etaria"] = "adulto"  # DataFrame, crie a coluna faixa_etaria e defina inicialmente todos os usuários como adultos.

In [102]:
df.loc[df["idade"] < 18, "faixa_etaria"] = "menor de idade"  # DataFrame, localize na coluna idade os usuários menores de 18 anos e altere a faixa_etaria para menor de idade.

In [103]:
df.loc[df["idade"].between(18, 29), "faixa_etaria"] = "adulto jovem"  # DataFrame, localize na coluna idade os usuários entre 18 e 29 anos e altere a faixa_etaria para adulto jovem.

In [104]:
df["faixa_etaria"].value_counts()  # Na coluna faixa_etaria, quantos usuários existem em cada categoria de idade?

faixa_etaria
adulto          23
adulto jovem     6
Name: count, dtype: int64

In [106]:
df.groupby(["faixa_etaria", "status"]).size()  # Agrupe pela faixa etária e pelo status e conte quantos atendimentos existem em cada grupo.

faixa_etaria  status
adulto        agendado      6
              cancelado     3
              concluido    14
adulto jovem  agendado      1
              cancelado     3
              concluido     2
dtype: int64

In [108]:
df.groupby(["faixa_etaria", "status"]).size().unstack(fill_value=0)  # Agrupe pela faixa etária e pelo status, conte os atendimentos e transforme os status em colunas preenchendo valores ausentes com zero.

status        agendado  cancelado  concluido
faixa_etaria
adulto               6          3         14
adulto jovem         1          3          2

In [112]:
df.groupby("faixa_etaria").size().sort_values(ascending=False)  # Agrupe pela faixa etária, conte os usuários e ordene da categoria com mais usuários para a com menos usuários.

faixa_etaria
adulto          23
adulto jovem     6
dtype: int64

In [113]:
df["idade"].apply(lambda idade: idade + 1)  # Acesse a coluna idade e aplique uma função que recebe cada idade e soma 1 ano.

0     31.0
1     38.0
2     41.0
3     36.0
4     53.0
6     29.0
7     46.0
8     68.0
9     30.0
10    38.0
11    39.0
12     NaN
13    23.0
14    42.0
15    35.0
16    40.0
17    28.0
18    64.0
19     NaN
20    32.0
21    36.0
22    50.0
23    27.0
24    59.0
25    38.0
26    37.0
27    44.0
28    20.0
30    34.0
Name: idade, dtype: float64

In [114]:
df["idade"] = df["idade"].apply(lambda idade: idade + 1)  # Acesse a coluna idade, aplique uma função que soma 1 ano e salve o resultado na própria coluna idade.

In [115]:
df["maioridade"] = df["idade"].apply(lambda idade: "menor de idade" if idade < 18 else "maior de idade")  # Crie ou acesse a coluna maioridade, aplique uma função à idade e classifique cada usuário como menor ou maior de idade.

In [116]:
def classificar_idade(idade):
    if idade < 18:
        return "menor de idade"
    elif idade < 60:
        return "adulto"
    else:
        return "idoso"

In [117]:
df["faixa_etaria"] = df["idade"].apply(classificar_idade)  # Acesse a coluna idade, aplique a função classificar_idade e salve o resultado na coluna faixa_etaria.

In [118]:
df["faixa_etaria"] = df["idade"].apply(
    lambda idade: "menor de idade" if idade < 18 else "adulto"
)  # Acesse a coluna idade, aplique uma função que classifica menores de 18 anos como menor de idade e os demais como adultos.

In [119]:
df["situacao"] = df["status"].apply(lambda status: "finalizado" if status == "concluido" else "em andamento")  # Crie a coluna situacao, aplique uma função ao status e classifique atendimentos concluídos como finalizados e os demais como em andamento.

In [ ]:
df["cidade"] = df["cidade"].apply(lambda cidade: cidade.strip().lower())  # Acesse a coluna cidade, aplique uma função que remove espaços e converte os textos para letras minúsculas e salve o resultado na própria coluna.

In [120]:
df.apply(lambda linha: linha["idade"] > 60, axis=1)  # Percorra cada linha da tabela DataFrame e verifique se a idade do usuário é maior que 60 anos.

0     False
1     False
2     False
3     False
4     False
6     False
7     False
8      True
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
30    False
dtype: bool

In [121]:
df["prioridade"] = df.apply(lambda linha: "alta" if linha["idade"] >= 60 or linha["status"] == "cancelado" else "normal",axis=1)
 # Crie a coluna prioridade, percorra cada linha e classifique como alta quando a idade for 60 ou mais ou o atendimento estiver cancelado; caso contrário, classifique como normal.

In [122]:
df["prioridade"].value_counts()  # Acesse a coluna prioridade e conte quantos usuários existem em cada nível de prioridade.

prioridade
normal    22
alta       7
Name: count, dtype: int64

In [123]:
df.groupby(["prioridade", "status"]).size()  # Agrupe pela prioridade e pelo status e conte quantos atendimentos existem em cada grupo.

prioridade  status
alta        cancelado     6
            concluido     1
normal      agendado      7
            concluido    15
dtype: int64

In [124]:
df[df["cidade"].str.contains("campinas")]  # Acesse a tabela DataFrame, filtre a coluna cidade e localize os registros que contêm a palavra campinas.

,id,nome,idade,cidade,especialidade,status,email,telefone,faixa_etaria,maioridade,situacao,prioridade
1,2,Ana Souza,38.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002,adulto,maior de idade,em andamento,normal
4,5,Joao Santos,53.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005,adulto,maior de idade,finalizado,normal
6,6,Pedro Oliveira,29.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006,adulto,maior de idade,finalizado,normal
7,7,Juliana Costa,46.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007,adulto,maior de idade,em andamento,normal
8,8,Marcos Pereira,68.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008,adulto,maior de idade,em andamento,alta
11,11,Patricia Lima,39.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011,adulto,maior de idade,finalizado,normal
14,14,Lucas Ferreira,42.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014,adulto,maior de idade,em andamento,normal
15,15,Amanda Rodrigues,35.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015,adulto,maior de idade,finalizado,normal
18,18,Thiago Alves,64.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018,adulto,maior de idade,finalizado,alta
20,20,Renata Costa,32.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020,adulto,maior de idade,finalizado,normal
22,22,Roberto Lima,50.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021,adulto,maior de idade,em andamento,alta
24,24,Daniel Souza,59.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023,adulto,maior de idade,finalizado,normal
26,26,Andre Pereira,37.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025,adulto,maior de idade,finalizado,normal
28,28,Mateus Costa,20.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027,adulto,maior de idade,em andamento,alta

In [125]:
df[df["especialidade"].str.contains("cardio")]  # Acesse a tabela DataFrame, filtre a coluna especialidade e localize os registros que contêm o texto cardio.

,id,nome,idade,cidade,especialidade,status,email,telefone,faixa_etaria,maioridade,situacao,prioridade
1,2,Ana Souza,38.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002,adulto,maior de idade,em andamento,normal
4,5,Joao Santos,53.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005,adulto,maior de idade,finalizado,normal
6,6,Pedro Oliveira,29.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006,adulto,maior de idade,finalizado,normal
7,7,Juliana Costa,46.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007,adulto,maior de idade,em andamento,normal
10,10,Rafael Souza,38.0,jundiai,cardiologia,agendado,rafael.souza@email.com,11999990010,adulto,maior de idade,em andamento,normal
14,14,Lucas Ferreira,42.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014,adulto,maior de idade,em andamento,normal
18,18,Thiago Alves,64.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018,adulto,maior de idade,finalizado,alta
22,22,Roberto Lima,50.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021,adulto,maior de idade,em andamento,alta
24,24,Daniel Souza,59.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023,adulto,maior de idade,finalizado,normal

In [126]:
df[df["cidade"].str.contains("Campinas", case=False)]  # Acesse a tabela DataFrame, filtre a coluna cidade e localize os registros que contêm campinas ignorando letras maiúsculas e minúsculas.

,id,nome,idade,cidade,especialidade,status,email,telefone,faixa_etaria,maioridade,situacao,prioridade
1,2,Ana Souza,38.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002,adulto,maior de idade,em andamento,normal
4,5,Joao Santos,53.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005,adulto,maior de idade,finalizado,normal
6,6,Pedro Oliveira,29.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006,adulto,maior de idade,finalizado,normal
7,7,Juliana Costa,46.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007,adulto,maior de idade,em andamento,normal
8,8,Marcos Pereira,68.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008,adulto,maior de idade,em andamento,alta
11,11,Patricia Lima,39.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011,adulto,maior de idade,finalizado,normal
14,14,Lucas Ferreira,42.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014,adulto,maior de idade,em andamento,normal
15,15,Amanda Rodrigues,35.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015,adulto,maior de idade,finalizado,normal
18,18,Thiago Alves,64.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018,adulto,maior de idade,finalizado,alta
20,20,Renata Costa,32.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020,adulto,maior de idade,finalizado,normal
22,22,Roberto Lima,50.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021,adulto,maior de idade,em andamento,alta
24,24,Daniel Souza,59.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023,adulto,maior de idade,finalizado,normal
26,26,Andre Pereira,37.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025,adulto,maior de idade,finalizado,normal
28,28,Mateus Costa,20.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027,adulto,maior de idade,em andamento,alta

In [127]:
df[df["cidade"].str.contains("campinas", na=False)]  # Acesse a tabela DataFrame, filtre a coluna cidade, procure campinas e considere valores ausentes como não encontrados.

,id,nome,idade,cidade,especialidade,status,email,telefone,faixa_etaria,maioridade,situacao,prioridade
1,2,Ana Souza,38.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002,adulto,maior de idade,em andamento,normal
4,5,Joao Santos,53.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005,adulto,maior de idade,finalizado,normal
6,6,Pedro Oliveira,29.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006,adulto,maior de idade,finalizado,normal
7,7,Juliana Costa,46.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007,adulto,maior de idade,em andamento,normal
8,8,Marcos Pereira,68.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008,adulto,maior de idade,em andamento,alta
11,11,Patricia Lima,39.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011,adulto,maior de idade,finalizado,normal
14,14,Lucas Ferreira,42.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014,adulto,maior de idade,em andamento,normal
15,15,Amanda Rodrigues,35.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015,adulto,maior de idade,finalizado,normal
18,18,Thiago Alves,64.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018,adulto,maior de idade,finalizado,alta
20,20,Renata Costa,32.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020,adulto,maior de idade,finalizado,normal
22,22,Roberto Lima,50.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021,adulto,maior de idade,em andamento,alta
24,24,Daniel Souza,59.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023,adulto,maior de idade,finalizado,normal
26,26,Andre Pereira,37.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025,adulto,maior de idade,finalizado,normal
28,28,Mateus Costa,20.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027,adulto,maior de idade,em andamento,alta

In [128]:
df[df["cidade"].str.contains("campinas", case=False, na=False)]  # Acesse a tabela DataFrame, filtre a coluna cidade e localize campinas ignorando maiúsculas, minúsculas e valores ausentes.

,id,nome,idade,cidade,especialidade,status,email,telefone,faixa_etaria,maioridade,situacao,prioridade
1,2,Ana Souza,38.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002,adulto,maior de idade,em andamento,normal
4,5,Joao Santos,53.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005,adulto,maior de idade,finalizado,normal
6,6,Pedro Oliveira,29.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006,adulto,maior de idade,finalizado,normal
7,7,Juliana Costa,46.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007,adulto,maior de idade,em andamento,normal
8,8,Marcos Pereira,68.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008,adulto,maior de idade,em andamento,alta
11,11,Patricia Lima,39.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011,adulto,maior de idade,finalizado,normal
14,14,Lucas Ferreira,42.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014,adulto,maior de idade,em andamento,normal
15,15,Amanda Rodrigues,35.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015,adulto,maior de idade,finalizado,normal
18,18,Thiago Alves,64.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018,adulto,maior de idade,finalizado,alta
20,20,Renata Costa,32.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020,adulto,maior de idade,finalizado,normal
22,22,Roberto Lima,50.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021,adulto,maior de idade,em andamento,alta
24,24,Daniel Souza,59.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023,adulto,maior de idade,finalizado,normal
26,26,Andre Pereira,37.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025,adulto,maior de idade,finalizado,normal
28,28,Mateus Costa,20.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027,adulto,maior de idade,em andamento,alta

In [129]:
df[df["cidade"].str.contains("campinas|vinhedo", case=False, na=False)]  # Acesse a tabela DataFrame, filtre a coluna cidade e localize registros que contêm campinas ou vinhedo.

,id,nome,idade,cidade,especialidade,status,email,telefone,faixa_etaria,maioridade,situacao,prioridade
0,1,Bruno Lima,31.0,vinhedo,clinico geral,concluido,bruno.lima@email.com,11999990001,adulto,maior de idade,finalizado,normal
1,2,Ana Souza,38.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002,adulto,maior de idade,em andamento,normal
4,5,Joao Santos,53.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005,adulto,maior de idade,finalizado,normal
6,6,Pedro Oliveira,29.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006,adulto,maior de idade,finalizado,normal
7,7,Juliana Costa,46.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007,adulto,maior de idade,em andamento,normal
8,8,Marcos Pereira,68.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008,adulto,maior de idade,em andamento,alta
9,9,Fernanda Alves,30.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009,adulto,maior de idade,finalizado,normal
11,11,Patricia Lima,39.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011,adulto,maior de idade,finalizado,normal
13,13,Beatriz Oliveira,23.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013,adulto,maior de idade,em andamento,alta
14,14,Lucas Ferreira,42.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014,adulto,maior de idade,em andamento,normal
15,15,Amanda Rodrigues,35.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015,adulto,maior de idade,finalizado,normal
18,18,Thiago Alves,64.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018,adulto,maior de idade,finalizado,alta
19,19,Julio Santos,NaN,vinhedo,clinico geral,agendado,julio.santos@email.com,11999990019,adulto,maior de idade,em andamento,normal
20,20,Renata Costa,32.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020,adulto,maior de idade,finalizado,normal
22,22,Roberto Lima,50.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021,adulto,maior de idade,em andamento,alta
23,23,Isabela Mendes,27.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022,adulto,maior de idade,em andamento,normal
24,24,Daniel Souza,59.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023,adulto,maior de idade,finalizado,normal
26,26,Andre Pereira,37.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025,adulto,maior de idade,finalizado,normal
27,27,Paula Fernandes,44.0,vinhedo,dermatologia,concluido,paula.fernandes@email.com,11999990026,adulto,maior de idade,finalizado,normal
28,28,Mateus Costa,20.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027,adulto,maior de idade,em andamento,alta

In [ ]:
df[~df["cidade"].str.contains("campinas", case=False, na=False)]  # Acesse a tabela DataFrame, filtre a coluna cidade e localize os registros que não contêm campinas ignorando maiúsculas, minúsculas e valores ausentes.

,id,nome,idade,cidade,especialidade,status,email,telefone,faixa_etaria,maioridade,situacao,prioridade
0,1,Bruno Lima,31.0,vinhedo,clinico geral,concluido,bruno.lima@email.com,11999990001,adulto,maior de idade,finalizado,normal
2,3,Carlos Mendes,41.0,jundiai,ortopedia,cancelado,carlos.mendes@email.com,11999990003,adulto,maior de idade,em andamento,alta
3,4,Mariana Silva,36.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004,adulto,maior de idade,finalizado,normal
9,9,Fernanda Alves,30.0,vinhedo,dermatologia,concluido,fernanda.alves@email.com,11999990009,adulto,maior de idade,finalizado,normal
10,10,Rafael Souza,38.0,jundiai,cardiologia,agendado,rafael.souza@email.com,11999990010,adulto,maior de idade,em andamento,normal
12,12,Gabriel Santos,NaN,valinhos,ortopedia,concluido,gabriel.santos@email.com,11999990012,adulto,maior de idade,finalizado,normal
13,13,Beatriz Oliveira,23.0,vinhedo,dermatologia,cancelado,beatriz.oliveira@email.com,11999990013,adulto,maior de idade,em andamento,alta
16,16,Diego Martins,40.0,jundiai,ortopedia,concluido,diego.martins@email.com,11999990016,adulto,maior de idade,finalizado,normal
17,17,Carolina Gomes,28.0,valinhos,dermatologia,cancelado,carolina.gomes@email.com,11999990017,adulto,maior de idade,em andamento,alta
19,19,Julio Santos,NaN,vinhedo,clinico geral,agendado,julio.santos@email.com,11999990019,adulto,maior de idade,em andamento,normal
21,21,Mariana Silva,36.0,valinhos,pediatria,concluido,mariana.silva@email.com,11999990004,adulto,maior de idade,finalizado,normal
23,23,Isabela Mendes,27.0,vinhedo,dermatologia,agendado,isabela.mendes@email.com,11999990022,adulto,maior de idade,em andamento,normal
25,25,Vanessa Oliveira,38.0,valinhos,pediatria,agendado,vanessa.oliveira@email.com,11999990024,adulto,maior de idade,em andamento,normal
27,27,Paula Fernandes,44.0,vinhedo,dermatologia,concluido,paula.fernandes@email.com,11999990026,adulto,maior de idade,finalizado,normal
30,30,Joana Alves,34.0,valinhos,pediatria,concluido,joana.alves@email.com,11999990028,adulto,maior de idade,finalizado,normal

In [131]:
df.loc[df["cidade"].str.contains("campinas", case=False, na=False)]  # Acesse a tabela DataFrame, localize na coluna cidade os registros que contêm campinas ignorando maiúsculas, minúsculas e valores ausentes.

,id,nome,idade,cidade,especialidade,status,email,telefone,faixa_etaria,maioridade,situacao,prioridade
1,2,Ana Souza,38.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002,adulto,maior de idade,em andamento,normal
4,5,Joao Santos,53.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005,adulto,maior de idade,finalizado,normal
6,6,Pedro Oliveira,29.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006,adulto,maior de idade,finalizado,normal
7,7,Juliana Costa,46.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007,adulto,maior de idade,em andamento,normal
8,8,Marcos Pereira,68.0,campinas,ortopedia,cancelado,marcos.pereira@email.com,11999990008,adulto,maior de idade,em andamento,alta
11,11,Patricia Lima,39.0,campinas,pediatria,concluido,patricia.lima@email.com,11999990011,adulto,maior de idade,finalizado,normal
14,14,Lucas Ferreira,42.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014,adulto,maior de idade,em andamento,normal
15,15,Amanda Rodrigues,35.0,campinas,pediatria,concluido,amanda.rodrigues@email.com,11999990015,adulto,maior de idade,finalizado,normal
18,18,Thiago Alves,64.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018,adulto,maior de idade,finalizado,alta
20,20,Renata Costa,32.0,campinas,pediatria,concluido,renata.costa@email.com,11999990020,adulto,maior de idade,finalizado,normal
22,22,Roberto Lima,50.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021,adulto,maior de idade,em andamento,alta
24,24,Daniel Souza,59.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023,adulto,maior de idade,finalizado,normal
26,26,Andre Pereira,37.0,campinas,ortopedia,concluido,andre.pereira@email.com,11999990025,adulto,maior de idade,finalizado,normal
28,28,Mateus Costa,20.0,campinas,clinico geral,cancelado,mateus.costa@email.com,11999990027,adulto,maior de idade,em andamento,alta

In [132]:
df.loc[
    df["cidade"].str.contains("campinas", case=False, na=False),
    ["nome", "cidade", "especialidade"]
]  # Acesse a tabela DataFrame, localize as cidades que contêm campinas e mostre apenas nome, cidade e especialidade.

                nome    cidade  especialidade
1          Ana Souza  campinas    cardiologia
4        Joao Santos  campinas    cardiologia
6     Pedro Oliveira  campinas    cardiologia
7      Juliana Costa  campinas    cardiologia
8     Marcos Pereira  campinas      ortopedia
11     Patricia Lima  campinas      pediatria
14    Lucas Ferreira  campinas    cardiologia
15  Amanda Rodrigues  campinas      pediatria
18      Thiago Alves  campinas    cardiologia
20      Renata Costa  campinas      pediatria
22      Roberto Lima  campinas    cardiologia
24      Daniel Souza  campinas    cardiologia
26     Andre Pereira  campinas      ortopedia
28      Mateus Costa  campinas  clinico geral

In [133]:
df[df["especialidade"].str.contains("cardio", case=False, na=False)]  # Acesse a tabela DataFrame, filtre a coluna especialidade e localize os atendimentos que contêm cardio ignorando maiúsculas, minúsculas e valores ausentes.

,id,nome,idade,cidade,especialidade,status,email,telefone,faixa_etaria,maioridade,situacao,prioridade
1,2,Ana Souza,38.0,campinas,cardiologia,agendado,ana.souza@email.com,11999990002,adulto,maior de idade,em andamento,normal
4,5,Joao Santos,53.0,campinas,cardiologia,concluido,joao.santos@email.com,11999990005,adulto,maior de idade,finalizado,normal
6,6,Pedro Oliveira,29.0,campinas,cardiologia,concluido,pedro.oliveira@email.com,11999990006,adulto,maior de idade,finalizado,normal
7,7,Juliana Costa,46.0,campinas,cardiologia,agendado,juliana.costa@email.com,11999990007,adulto,maior de idade,em andamento,normal
10,10,Rafael Souza,38.0,jundiai,cardiologia,agendado,rafael.souza@email.com,11999990010,adulto,maior de idade,em andamento,normal
14,14,Lucas Ferreira,42.0,campinas,cardiologia,agendado,lucas.ferreira@email.com,11999990014,adulto,maior de idade,em andamento,normal
18,18,Thiago Alves,64.0,campinas,cardiologia,concluido,thiago.alves@email.com,11999990018,adulto,maior de idade,finalizado,alta
22,22,Roberto Lima,50.0,campinas,cardiologia,cancelado,roberto.lima@email.com,11999990021,adulto,maior de idade,em andamento,alta
24,24,Daniel Souza,59.0,campinas,cardiologia,concluido,daniel.souza@email.com,11999990023,adulto,maior de idade,finalizado,normal

In [134]:
df[df["especialidade"].str.contains("cardio", case=False, na=False)].shape[0]  # Acesse a tabela DataFrame, filtre as especialidades que contêm cardio e conte quantas linhas foram encontradas.

9

In [135]:
df[df["especialidade"].str.contains("cardio", case=False, na=False)]["status"].value_counts()  # Acesse a tabela DataFrame, filtre as especialidades que contêm cardio, acesse a coluna status e conte a frequência de cada status.

status
agendado     4
concluido    4
cancelado    1
Name: count, dtype: int64

In [136]:
df["cidade"] = df["cidade"].str.replace("sao paulo", "são paulo")  # Acesse a coluna cidade, substitua o texto sao paulo pelo texto são paulo e salve o resultado novamente na coluna cidade.

In [137]:
df["especialidade"] = df["especialidade"].str.replace(" ", "_")  # Acesse a coluna especialidade, substitua os espaços por underline e salve o resultado novamente na coluna especialidade.

In [138]:
df["cidade"] = df["cidade"].str.replace(" - SP", "")  # Acesse a coluna cidade, substitua o texto - SP por nada e salve o resultado novamente na coluna cidade.

In [139]:
df["especialidade"] = df["especialidade"].str.replace("cardio", "CARDIO", n=1)  # Acesse a coluna especialidade, substitua apenas a primeira ocorrência de cardio por CARDIO e salve o resultado novamente na coluna especialidade.

In [ ]:
df["cidade"] = df["cidade"].str.strip().str.replace("sao paulo", "são paulo")  # Acesse a coluna cidade, remova espaços no início e no final, substitua sao paulo por são paulo e salve o resultado novamente na coluna cidade.

In [140]:
df["status"] = df["status"].str.upper()  # Acesse a coluna status, transforme todos os textos para letras maiúsculas e salve o resultado novamente na coluna status.

In [141]:
df["cidade"] = df["cidade"].str.title()  # Acesse a coluna cidade, transforme a primeira letra de cada palavra para maiúscula e salve o resultado novamente na coluna cidade.

In [142]:
df["cidade"] = df["cidade"].str.lower()  # Acesse a coluna cidade, transforme os textos em letras minúsculas e salve o resultado novamente na coluna cidade.

In [143]:
df["cidade"] = df["cidade"].str.title()  # Acesse a coluna cidade, transforme cada palavra para o formato de título e salve o resultado novamente na coluna cidade.

In [144]:
df.dtypes  # Acesse a tabela DataFrame e mostre o tipo de dado armazenado em cada coluna.

id                 int64
nome                 str
idade            float64
cidade               str
especialidade        str
status               str
email                str
telefone           int64
faixa_etaria         str
maioridade           str
situacao             str
prioridade           str
dtype: object

In [147]:
df["idade"] = df["idade"].astype(str)  # Acesse a coluna idade, converta os valores para texto e salve o resultado novamente na coluna idade.

df["idade"]

0     31.0
1     38.0
2     41.0
3     36.0
4     53.0
6     29.0
7     46.0
8     68.0
9     30.0
10    38.0
11    39.0
12     NaN
13    23.0
14    42.0
15    35.0
16    40.0
17    28.0
18    64.0
19     NaN
20    32.0
21    36.0
22    50.0
23    27.0
24    59.0
25    38.0
26    37.0
27    44.0
28    20.0
30    34.0
Name: idade, dtype: str

In [148]:
df["idade"].dtype  # Acesse a coluna idade e mostre o tipo de dado armazenado nela.

In [152]:
df["idade"] = df["idade"].astype(str).astype(float)  # Acesse a coluna idade, converta os valores de texto para números decimais, depois converta os números decimais para inteiros e salve o resultado novamente na coluna idade.

In [154]:
df["idade"] = df["idade"].astype(float).astype("Int64")  # Acesse a coluna idade, converta os valores de texto para números decimais, depois converta os números decimais para inteiros e salve o resultado novamente na coluna idade.

In [156]:
df["idade"] = pd.to_numeric(df["idade"])  # Acesse a coluna idade, converta os valores para números e salve o resultado novamente na coluna idade.
df["idade"]

0       31
1       38
2       41
3       36
4       53
6       29
7       46
8       68
9       30
10      38
11      39
12    <NA>
13      23
14      42
15      35
16      40
17      28
18      64
19    <NA>
20      32
21      36
22      50
23      27
24      59
25      38
26      37
27      44
28      20
30      34
Name: idade, dtype: Int64

In [158]:
df["idade"] = pd.to_numeric(df["idade"], errors="coerce")  # Acesse a coluna idade, converta os valores para números, transforme valores inválidos em ausentes e salve o resultado novamente na coluna idade.
df["idade"]

0       31
1       38
2       41
3       36
4       53
6       29
7       46
8       68
9       30
10      38
11      39
12    <NA>
13      23
14      42
15      35
16      40
17      28
18      64
19    <NA>
20      32
21      36
22      50
23      27
24      59
25      38
26      37
27      44
28      20
30      34
Name: idade, dtype: Int64

In [159]:
df["idade"].isnull().sum()  # Acesse a coluna idade, identifique os valores ausentes e conte quantos existem.

np.int64(2)

In [160]:
df["idade"] = pd.to_numeric(df["idade"], errors="coerce")  # Acesse a coluna idade, converta os valores para números, transforme valores inválidos em ausentes e salve o resultado novamente na coluna idade.

df["idade"] = df["idade"].fillna(df["idade"].median())  # Acesse a coluna idade, substitua os valores ausentes pela mediana das idades e salve o resultado novamente na coluna idade.

In [168]:
df["data"] = pd.to_datetime(df["data"])  # Acesse a coluna data, converta os valores para o formato de data e salve o resultado novamente na coluna data.
df["data"]

0    2026-01-15
1    2026-01-20
2    2026-02-05
3    2026-02-10
4    2026-02-15
5    2026-02-15
6    2026-02-20
7    2026-03-01
8    2026-03-05
9    2026-03-10
10   2026-03-15
11   2026-03-20
12   2026-04-01
13   2026-04-05
14   2026-04-10
15   2026-04-15
16   2026-04-20
17   2026-05-01
18   2026-05-05
19   2026-05-10
20   2026-05-15
21   2026-05-20
22   2026-06-01
23   2026-06-05
24   2026-06-10
25   2026-06-15
26   2026-06-20
27   2026-07-01
28   2026-07-05
29   2026-07-10
30   2026-07-15
Name: data, dtype: datetime64[us]

In [171]:
df["data"].dtype  # Acesse a coluna data e mostre o tipo de dado armazenado nela após a conversão.

dtype('<M8[us]')

In [172]:
df["data"].dt.year  # Acesse a coluna data, acesse o componente de ano de cada data e exiba os anos encontrados.

0     2026
1     2026
2     2026
3     2026
4     2026
5     2026
6     2026
7     2026
8     2026
9     2026
10    2026
11    2026
12    2026
13    2026
14    2026
15    2026
16    2026
17    2026
18    2026
19    2026
20    2026
21    2026
22    2026
23    2026
24    2026
25    2026
26    2026
27    2026
28    2026
29    2026
30    2026
Name: data, dtype: int32

In [174]:
df["mes"] = df["data"].dt.month  # Acesse a coluna data, extraia o número do mês de cada registro e salve os resultados em uma nova coluna chamada mes.
df["mes"]

0     1
1     1
2     2
3     2
4     2
5     2
6     2
7     3
8     3
9     3
10    3
11    3
12    4
13    4
14    4
15    4
16    4
17    5
18    5
19    5
20    5
21    5
22    6
23    6
24    6
25    6
26    6
27    7
28    7
29    7
30    7
Name: mes, dtype: int32

In [183]:
df["dia"] = df["data"].dt.day  # Acesse a coluna data, extraia o dia de cada registro e salve os resultados em uma nova coluna chamada dia.

In [184]:
df["data"] = pd.to_datetime(df["data"], errors="coerce")  # Acesse a coluna data, tente converter os valores para data e transforme valores que não podem ser convertidos em valores ausentes.
df["data"]

0    2026-01-15
1    2026-01-20
2    2026-02-05
3    2026-02-10
4    2026-02-15
5    2026-02-15
6    2026-02-20
7    2026-03-01
8    2026-03-05
9    2026-03-10
10   2026-03-15
11   2026-03-20
12   2026-04-01
13   2026-04-05
14   2026-04-10
15   2026-04-15
16   2026-04-20
17   2026-05-01
18   2026-05-05
19   2026-05-10
20   2026-05-15
21   2026-05-20
22   2026-06-01
23   2026-06-05
24   2026-06-10
25   2026-06-15
26   2026-06-20
27   2026-07-01
28   2026-07-05
29   2026-07-10
30   2026-07-15
Name: data, dtype: datetime64[us]

In [185]:
df["data"].iloc[24:27]  # Acesse a coluna data, localize as posições 24 até 26 e exiba esses valores.

24   2026-06-10
25   2026-06-15
26   2026-06-20
Name: data, dtype: datetime64[us]

In [186]:
df[df["data"] > "2026-05-01"]  # Acesse a tabela DataFrame, filtre os registros onde a coluna data possui valores posteriores a 1 de maio de 2026.

,id,nome,idade,cidade,especialidade,status,email,telefone,data,mes,dia
18,18,Thiago Alves,63.0,Campinas,Cardiologia,Concluido,thiago.alves@email.com,11999990018,2026-05-05,5,5
19,19,Julio Santos,-5.0,Vinhedo,Clinico Geral,Agendado,julio.santos@email.com,11999990019,2026-05-10,5,10
20,20,Renata Costa,31.0,Campinas,Pediatria,Concluido,renata.costa@email.com,11999990020,2026-05-15,5,15
21,21,Mariana Silva,35.0,Valinhos,Pediatria,Concluido,mariana.silva@email.com,11999990004,2026-05-20,5,20
22,22,Roberto Lima,49.0,Campinas,Cardiologia,Cancelado,roberto.lima@email.com,11999990021,2026-06-01,6,1
23,23,Isabela Mendes,26.0,Vinhedo,Dermatologia,Agendado,isabela.mendes@email.com,11999990022,2026-06-05,6,5
24,24,Daniel Souza,58.0,Campinas,Cardiologia,Concluido,daniel.souza@email.com,11999990023,2026-06-10,6,10
25,25,Vanessa Oliveira,NaN,Valinhos,Pediatria,Agendado,vanessa.oliveira@email.com,11999990024,2026-06-15,6,15
26,26,Andre Pereira,36.0,Campinas,Ortopedia,Concluido,andre.pereira@email.com,11999990025,2026-06-20,6,20
27,27,Paula Fernandes,43.0,Vinhedo,Dermatologia,CONCLUIDO,paula.fernandes@email.com,11999990026,2026-07-01,7,1
28,28,Mateus Costa,19.0,Campinas,Clinico Geral,Cancelado,mateus.costa@email.com,11999990027,2026-07-05,7,5
29,29,Lucas Ferreira,41.0,Campinas,Cardiologia,Agendado,lucas.ferreira@email.com,11999990014,2026-07-10,7,10
30,30,Joana Alves,33.0,Valinhos,Pediatria,Concluido,joana.alves@email.com,11999990028,2026-07-15,7,15

In [ ]:
df[df["data"] < "2026-05-01"]  # Acesse a tabela DataFrame, filtre os registros onde a coluna data possui valores anteriores a 1 de maio de 2026.

,id,nome,idade,cidade,especialidade,status,email,telefone,data,mes,dia
0,1,Bruno Lima,30.0,Vinhedo,Clinico Geral,Concluido,bruno.lima@email.com,11999990001,2026-01-15,1,15
1,2,Ana Souza,NaN,Campinas,Cardiologia,Agendado,ana.souza@email.com,11999990002,2026-01-20,1,20
2,3,Carlos Mendes,40.0,Jundiai,Ortopedia,Cancelado,carlos.mendes@email.com,11999990003,2026-02-05,2,5
3,4,Mariana Silva,35.0,Valinhos,Pediatria,Concluido,mariana.silva@email.com,11999990004,2026-02-10,2,10
4,5,Joao Santos,52.0,Campinas,Cardiologia,Concluido,joao.santos@email.com,11999990005,2026-02-15,2,15
5,5,Joao Santos,52.0,Campinas,Cardiologia,Concluido,joao.santos@email.com,11999990005,2026-02-15,2,15
6,6,Pedro Oliveira,28.0,Campinas,Cardiologia,concluido,pedro.oliveira@email.com,11999990006,2026-02-20,2,20
7,7,Juliana Costa,45.0,CAMPINAS,cardiologia,AGENDADO,juliana.costa@email.com,11999990007,2026-03-01,3,1
8,8,Marcos Pereira,67.0,Campinas,ORTOPEDIA,Cancelado,marcos.pereira@email.com,11999990008,2026-03-05,3,5
9,9,Fernanda Alves,29.0,Vinhedo,Dermatologia,Concluido,fernanda.alves@email.com,11999990009,2026-03-10,3,10
10,10,Rafael Souza,NaN,Jundiai,Cardiologia,agendado,rafael.souza@email.com,11999990010,2026-03-15,3,15
11,11,Patricia Lima,38.0,Campinas,Pediatria,CONCLUIDO,patricia.lima@email.com,11999990011,2026-03-20,3,20
12,12,Gabriel Santos,150.0,Valinhos,Ortopedia,Concluido,gabriel.santos@email.com,11999990012,2026-04-01,4,1
13,13,Beatriz Oliveira,22.0,Vinhedo,Dermatologia,Cancelado,beatriz.oliveira@email.com,11999990013,2026-04-05,4,5
14,14,Lucas Ferreira,41.0,Campinas,Cardiologia,Agendado,lucas.ferreira@email.com,11999990014,2026-04-10,4,10
15,15,Amanda Rodrigues,34.0,Campinas,Pediatria,Concluido,amanda.rodrigues@email.com,11999990015,2026-04-15,4,15
16,16,Diego Martins,39.0,JUNDIAI,Ortopedia,concluido,diego.martins@email.com,11999990016,2026-04-20,4,20

In [190]:
df[(df["data"] >= "2026-03-01") & (df["data"] <= "2026-05-31")]  # Acesse a tabela DataFrame, filtre as datas a partir de 1 de março de 2026 e até 31 de maio de 2026.

,id,nome,idade,cidade,especialidade,status,email,telefone,data,mes,dia,ano
7,7,Juliana Costa,45.0,CAMPINAS,cardiologia,AGENDADO,juliana.costa@email.com,11999990007,2026-03-01,3,1,2026
8,8,Marcos Pereira,67.0,Campinas,ORTOPEDIA,Cancelado,marcos.pereira@email.com,11999990008,2026-03-05,3,5,2026
9,9,Fernanda Alves,29.0,Vinhedo,Dermatologia,Concluido,fernanda.alves@email.com,11999990009,2026-03-10,3,10,2026
10,10,Rafael Souza,NaN,Jundiai,Cardiologia,agendado,rafael.souza@email.com,11999990010,2026-03-15,3,15,2026
11,11,Patricia Lima,38.0,Campinas,Pediatria,CONCLUIDO,patricia.lima@email.com,11999990011,2026-03-20,3,20,2026
12,12,Gabriel Santos,150.0,Valinhos,Ortopedia,Concluido,gabriel.santos@email.com,11999990012,2026-04-01,4,1,2026
13,13,Beatriz Oliveira,22.0,Vinhedo,Dermatologia,Cancelado,beatriz.oliveira@email.com,11999990013,2026-04-05,4,5,2026
14,14,Lucas Ferreira,41.0,Campinas,Cardiologia,Agendado,lucas.ferreira@email.com,11999990014,2026-04-10,4,10,2026
15,15,Amanda Rodrigues,34.0,Campinas,Pediatria,Concluido,amanda.rodrigues@email.com,11999990015,2026-04-15,4,15,2026
16,16,Diego Martins,39.0,JUNDIAI,Ortopedia,concluido,diego.martins@email.com,11999990016,2026-04-20,4,20,2026
17,17,Carolina Gomes,27.0,Valinhos,Dermatologia,Cancelado,carolina.gomes@email.com,11999990017,2026-05-01,5,1,2026
18,18,Thiago Alves,63.0,Campinas,Cardiologia,Concluido,thiago.alves@email.com,11999990018,2026-05-05,5,5,2026
19,19,Julio Santos,-5.0,Vinhedo,Clinico Geral,Agendado,julio.santos@email.com,11999990019,2026-05-10,5,10,2026
20,20,Renata Costa,31.0,Campinas,Pediatria,Concluido,renata.costa@email.com,11999990020,2026-05-15,5,15,2026
21,21,Mariana Silva,35.0,Valinhos,Pediatria,Concluido,mariana.silva@email.com,11999990004,2026-05-20,5,20,2026

In [189]:
df["ano"] = df["data"].dt.year  # Acesse a coluna data, extraia o ano de cada registro e salve o resultado em uma nova coluna chamada ano.

In [191]:
df["mes"].value_counts()  # Acesse a coluna mes e conte quantos registros existem em cada mês.

mes
2    5
3    5
4    5
5    5
6    5
7    4
1    2
Name: count, dtype: int64

In [192]:
df["mes"].value_counts().idxmax()  # Acesse a coluna mes, conte a frequência de cada mês e retorne o mês que possui a maior frequência.

np.int32(2)

In [193]:
df["mes"].value_counts().max()  # Acesse a coluna mes, conte a frequência de cada mês e retorne a maior quantidade encontrada.

np.int64(5)

In [194]:
df.groupby("mes").size()  # Acesse a tabela DataFrame, agrupe os registros pelo mês e conte quantos registros existem em cada grupo.

mes
1    2
2    5
3    5
4    5
5    5
6    5
7    4
dtype: int64

In [195]:
df.groupby(["mes", "status"]).size()  # Acesse a tabela DataFrame, agrupe os registros pelo mês e pelo status e conte quantos registros existem em cada combinação.

mes  status
1    Agendado     1
     Concluido    1
2    Cancelado    1
     Concluido    3
     concluido    1
3    AGENDADO     1
     CONCLUIDO    1
     Cancelado    1
     Concluido    1
     agendado     1
4    Agendado     1
     Cancelado    1
     Concluido    2
     concluido    1
5    Agendado     1
     Cancelado    1
     Concluido    3
6    Agendado     2
     Cancelado    1
     Concluido    2
7    Agendado     1
     CONCLUIDO    1
     Cancelado    1
     Concluido    1
dtype: int64

In [196]:
df["data"].dt.day_name()  # Acesse a coluna data, extraia o nome do dia da semana de cada data e exiba os resultados.

0      Thursday
1       Tuesday
2      Thursday
3       Tuesday
4        Sunday
5        Sunday
6        Friday
7        Sunday
8      Thursday
9       Tuesday
10       Sunday
11       Friday
12    Wednesday
13       Sunday
14       Friday
15    Wednesday
16       Monday
17       Friday
18      Tuesday
19       Sunday
20       Friday
21    Wednesday
22       Monday
23       Friday
24    Wednesday
25       Monday
26     Saturday
27    Wednesday
28       Sunday
29       Friday
30    Wednesday
Name: data, dtype: str

In [204]:
df["dia_semana_nome"] = df["data"].dt.day_name(locale="pt_BR")  # Acesse a coluna data, extraia o nome do dia da semana em português e salve o resultado em uma nova coluna.
df["dia_semana_nome"]  # Exiba os resultados da nova coluna.

0      Quinta-feira
1       Terça-feira
2      Quinta-feira
3       Terça-feira
4           Domingo
5           Domingo
6       Sexta-feira
7           Domingo
8      Quinta-feira
9       Terça-feira
10          Domingo
11      Sexta-feira
12     Quarta-feira
13          Domingo
14      Sexta-feira
15     Quarta-feira
16    Segunda-feira
17      Sexta-feira
18      Terça-feira
19          Domingo
20      Sexta-feira
21     Quarta-feira
22    Segunda-feira
23      Sexta-feira
24     Quarta-feira
25    Segunda-feira
26           Sábado
27     Quarta-feira
28          Domingo
29      Sexta-feira
30     Quarta-feira
Name: dia_semana_nome, dtype: str

In [198]:
df["data"].dt.dayofweek  # Acesse a coluna data, extraia o número correspondente ao dia da semana e exiba os resultados.

0     3
1     1
2     3
3     1
4     6
5     6
6     4
7     6
8     3
9     1
10    6
11    4
12    2
13    6
14    4
15    2
16    0
17    4
18    1
19    6
20    4
21    2
22    0
23    4
24    2
25    0
26    5
27    2
28    6
29    4
30    2
Name: data, dtype: int32

In [200]:
df["dia_semana"] = df["data"].dt.dayofweek  # Acesse a coluna data, extraia o número do dia da semana e salve o resultado em uma nova coluna chamada dia_semana.
df["dia_semana"]

0     3
1     1
2     3
3     1
4     6
5     6
6     4
7     6
8     3
9     1
10    6
11    4
12    2
13    6
14    4
15    2
16    0
17    4
18    1
19    6
20    4
21    2
22    0
23    4
24    2
25    0
26    5
27    2
28    6
29    4
30    2
Name: dia_semana, dtype: int32

In [201]:
df["dia_semana"].value_counts()  # Acesse a coluna dia_semana e conte quantos atendimentos existem em cada dia da semana.

dia_semana
6    7
4    7
2    6
1    4
3    3
0    3
5    1
Name: count, dtype: int64

In [202]:
dias = [
    "segunda-feira",
    "terça-feira",
    "quarta-feira",
    "quinta-feira",
    "sexta-feira",
    "sábado",
    "domingo"
]  # Crie uma lista contendo os nomes dos dias da semana na ordem utilizada pelo Pandas.

In [203]:
df["dia_semana_nome"] = df["data"].dt.dayofweek.map(lambda x: dias[x])  # Acesse a coluna data, extraia o número do dia da semana, procure o nome correspondente na lista dias e salve o resultado em uma nova coluna.
df["dia_semana_nome"]  # Exiba os resultados da nova coluna.

0      quinta-feira
1       terça-feira
2      quinta-feira
3       terça-feira
4           domingo
5           domingo
6       sexta-feira
7           domingo
8      quinta-feira
9       terça-feira
10          domingo
11      sexta-feira
12     quarta-feira
13          domingo
14      sexta-feira
15     quarta-feira
16    segunda-feira
17      sexta-feira
18      terça-feira
19          domingo
20      sexta-feira
21     quarta-feira
22    segunda-feira
23      sexta-feira
24     quarta-feira
25    segunda-feira
26           sábado
27     quarta-feira
28          domingo
29      sexta-feira
30     quarta-feira
Name: dia_semana_nome, dtype: str

In [205]:
df["dia_semana_nome"].value_counts()  # Acesse a coluna dia_semana_nome e conte a frequência de cada dia da semana.

dia_semana_nome
Domingo          7
Sexta-feira      7
Quarta-feira     6
Terça-feira      4
Quinta-feira     3
Segunda-feira    3
Sábado           1
Name: count, dtype: int64

In [206]:
df["dia_semana_nome"].value_counts().idxmax()  # Acesse a coluna dia_semana_nome, conte a frequência de cada dia e retorne o dia da semana mais frequente.

'Domingo'

In [207]:
df["dia_semana_nome"].value_counts().max()  # Acesse a coluna dia_semana_nome, conte a frequência de cada dia e retorne a maior quantidade encontrada.

np.int64(7)

In [208]:
df.groupby(["dia_semana_nome", "status"]).size()  # Acesse a tabela DataFrame, agrupe os registros pelo dia da semana e pelo status e conte quantos registros existem em cada combinação.

dia_semana_nome  status
Domingo          AGENDADO     1
                 Agendado     1
                 Cancelado    2
                 Concluido    2
                 agendado     1
Quarta-feira     CONCLUIDO    1
                 Concluido    5
Quinta-feira     Cancelado    2
                 Concluido    1
Segunda-feira    Agendado     1
                 Cancelado    1
                 concluido    1
Sexta-feira      Agendado     3
                 CONCLUIDO    1
                 Cancelado    1
                 Concluido    1
                 concluido    1
Sábado           Concluido    1
Terça-feira      Agendado     1
                 Concluido    3
dtype: int64

In [209]:
df[df["especialidade"] == "cardiologia"]["dia_semana_nome"].value_counts()  # Acesse a tabela DataFrame, filtre as especialidades de cardiologia, acesse a coluna dia_semana_nome e conte a frequência de cada dia da semana.

dia_semana_nome
Domingo    1
Name: count, dtype: int64

In [210]:
df["data_retorno"] = df["data"] + pd.Timedelta(days=7)  # Acesse a coluna data, adicione 7 dias a cada data e salve o resultado em uma nova coluna chamada data_retorno.
df["data_retorno"]  # Exiba os resultados da nova coluna.

0    2026-01-22
1    2026-01-27
2    2026-02-12
3    2026-02-17
4    2026-02-22
5    2026-02-22
6    2026-02-27
7    2026-03-08
8    2026-03-12
9    2026-03-17
10   2026-03-22
11   2026-03-27
12   2026-04-08
13   2026-04-12
14   2026-04-17
15   2026-04-22
16   2026-04-27
17   2026-05-08
18   2026-05-12
19   2026-05-17
20   2026-05-22
21   2026-05-27
22   2026-06-08
23   2026-06-12
24   2026-06-17
25   2026-06-22
26   2026-06-27
27   2026-07-08
28   2026-07-12
29   2026-07-17
30   2026-07-22
Name: data_retorno, dtype: datetime64[us]

In [211]:
df[["data", "data_retorno"]]  # Acesse a tabela DataFrame, selecione as colunas data e data_retorno e exiba os resultados.

         data data_retorno
0  2026-01-15   2026-01-22
1  2026-01-20   2026-01-27
2  2026-02-05   2026-02-12
3  2026-02-10   2026-02-17
4  2026-02-15   2026-02-22
5  2026-02-15   2026-02-22
6  2026-02-20   2026-02-27
7  2026-03-01   2026-03-08
8  2026-03-05   2026-03-12
9  2026-03-10   2026-03-17
10 2026-03-15   2026-03-22
11 2026-03-20   2026-03-27
12 2026-04-01   2026-04-08
13 2026-04-05   2026-04-12
14 2026-04-10   2026-04-17
15 2026-04-15   2026-04-22
16 2026-04-20   2026-04-27
17 2026-05-01   2026-05-08
18 2026-05-05   2026-05-12
19 2026-05-10   2026-05-17
20 2026-05-15   2026-05-22
21 2026-05-20   2026-05-27
22 2026-06-01   2026-06-08
23 2026-06-05   2026-06-12
24 2026-06-10   2026-06-17
25 2026-06-15   2026-06-22
26 2026-06-20   2026-06-27
27 2026-07-01   2026-07-08
28 2026-07-05   2026-07-12
29 2026-07-10   2026-07-17
30 2026-07-15   2026-07-22

In [212]:
df["data_retorno"] - df["data"]  # Acesse a coluna data_retorno, subtraia a coluna data e calcule a diferença entre as duas datas.

0    7 days
1    7 days
2    7 days
3    7 days
4    7 days
5    7 days
6    7 days
7    7 days
8    7 days
9    7 days
10   7 days
11   7 days
12   7 days
13   7 days
14   7 days
15   7 days
16   7 days
17   7 days
18   7 days
19   7 days
20   7 days
21   7 days
22   7 days
23   7 days
24   7 days
25   7 days
26   7 days
27   7 days
28   7 days
29   7 days
30   7 days
dtype: timedelta64[us]

In [213]:
df["dias_ate_retorno"] = df["data_retorno"] - df["data"]  # Acesse a coluna data_retorno, subtraia a coluna data e salve o intervalo de tempo em uma nova coluna chamada dias_ate_retorno.

In [214]:
df["dias_ate_retorno"] = (df["data_retorno"] - df["data"]).dt.days  # Acesse a coluna data_retorno, subtraia a coluna data, extraia a quantidade de dias do intervalo e salve o resultado na coluna dias_ate_retorno.

In [215]:
df["data_retorno_30"] = df["data"] + pd.Timedelta(days=30)  # Acesse a coluna data, adicione 30 dias a cada data e salve o resultado em uma nova coluna chamada data_retorno_30.

In [216]:
df["data_retorno_15"] = df["data"] + pd.Timedelta(days=15)  # Acesse a coluna data, adicione 15 dias a cada data e salve o resultado em uma nova coluna chamada data_retorno_15.

In [217]:
df["data_anterior"] = df["data"] - pd.Timedelta(days=7)  # Acesse a coluna data, subtraia 7 dias de cada data e salve o resultado em uma nova coluna chamada data_anterior.

In [218]:
pd.Timedelta(hours=24)  # Crie um intervalo de tempo correspondente a 24 horas.

Timedelta('1 days 00:00:00')

In [219]:
pd.Timedelta(days=2, hours=5)  # Crie um intervalo de tempo correspondente a 2 dias e 5 horas.

Timedelta('2 days 05:00:00')

In [220]:
pd.Timedelta(minutes=30)  # Crie um intervalo de tempo correspondente a 30 minutos.

Timedelta('0 days 00:30:00')